name: mobile_challenge
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  loading_animation_widget: ^1.2.0+4
  awesome_snackbar_content: ^0.1.3
  get_it: ^7.6.0
  dio: ^5.2.1+1
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  hive_generator: ^2.0.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0


flutter:
  uses-material-design: true

  assets:
    - assets/json/words_dictionary.json
    - .env

  fonts:
    - family: mplus1
      fonts:
        - asset: assets/fonts/mplus1/MPLUS1p-Light.ttf
          weight: 300
        - asset: assets/fonts/mplus1/MPLUS1p-Regular.ttf
          style: normal
        - asset: assets/fonts/mplus1/MPLUS1p-Medium.ttf
          weight: 500
        - asset: assets/fonts/mplus1/MPLUS1p-Bold.ttf
          weight: 700
        - asset: assets/fonts/mplus1/MPLUS1p-ExtraBold.ttf
          weight: 800
